export { default as testAxiosRouter } from './axios'
export { default as testVue2Router } from './vue2'
export { default as testElementUiRouter } from './element-ui'
export { default as testVueEchartsRouter } from './vue-echarts'
export { default as formMakingsRouter } from './form-making'
