export default [
  {
      "dataDirectory": "结算价",
      "id": "1572133730540707842",
      "primaryElement": "相关品价格",
      "relationTemplate": "",
      "ringRatio": "0.00%",
      "ringRatioValue": 3753,
      "secondaryElements": "盘面",
      "sort": 1,
      "thirdLevelElements": "主力合约",
      "usingFlag": "1",
      "value": 3753,
      "valueCode": "RELATED_PRICE_MAIN_CONTRACT_SETTLEMENT_PRICE",
      "whetherItem": "0",
      "yearOnYear": "23.78%",
      "yearOnYearValue": 3032
  },
  {
      "dataDirectory": "结算价",
      "id": "1572133832667815937",
      "primaryElement": "相关品价格",
      "relationTemplate": "",
      "ringRatio": "0.00%",
      "ringRatioValue": 3566,
      "secondaryElements": "盘面",
      "sort": 2,
      "thirdLevelElements": "次主力合约",
      "usingFlag": "1",
      "value": 3566,
      "valueCode": "RELATED_PRICE_NEXT_MAIN_CONTRACT_SETTLEMENT_PRICE",
      "whetherItem": "0",
      "yearOnYear": "16.38%",
      "yearOnYearValue": 3064
  },
  {
      "dataDirectory": "价格",
      "id": "1572133958303997953",
      "primaryElement": "相关品价格",
      "relationTemplate": "",
      "secondaryElements": "原料",
      "sort": 3,
      "thirdLevelElements": "即期国际油价",
      "usingFlag": "1",
      "value": 95.86,
      "valueCode": "RELATED_PRICE_MATERIAL_SPOT_INTER_OIL_PRICE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "价格",
      "id": "1572134050574491649",
      "primaryElement": "相关品价格",
      "relationTemplate": "",
      "secondaryElements": "原料",
      "sort": 4,
      "thirdLevelElements": "贴水",
      "usingFlag": "1",
      "value": -17.1,
      "valueCode": "RELATED_PRICE_MATERIAL_DISCOUNT",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "价格",
      "id": "1572134143172141058",
      "primaryElement": "相关品价格",
      "relationTemplate": "",
      "secondaryElements": "原料",
      "sort": 5,
      "thirdLevelElements": "到司价格",
      "usingFlag": "1",
      "value": 5183,
      "valueCode": "RELATED_PRICE_MATERIAL_ARRIVAL_PRICE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "价格",
      "id": "1572134336017850369",
      "primaryElement": "相关品价格",
      "relationTemplate": "",
      "secondaryElements": "成品油",
      "sort": 6,
      "thirdLevelElements": "柴油",
      "usingFlag": "1",
      "value": 8697,
      "valueCode": "RELATED_PRICE_REFINED_OIL_DIESEL_PRICE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "价格",
      "id": "1572134435326386177",
      "primaryElement": "相关品价格",
      "relationTemplate": "",
      "secondaryElements": "成品油",
      "sort": 7,
      "thirdLevelElements": "汽油",
      "usingFlag": "1",
      "value": 8044,
      "valueCode": "RELATED_PRICE_REFINED_OIL_GASOLINE_PRICE",
      "whetherItem": "0"
  },
  {
      "evaluate": "",
      "id": "1572134574648582146",
      "primaryElement": "相关品价格评价",
      "relationTemplate": "",
      "sort": 8,
      "usingFlag": "1",
      "valueCode": "RELATED_PRICE_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "基差",
      "id": "1572134783243902978",
      "primaryElement": "基差",
      "relationTemplate": "",
      "secondaryElements": "主力合约",
      "sort": 9,
      "thirdLevelElements": "山东",
      "usingFlag": "1",
      "valueCode": "BASIS_MAIN_CONTRACT_SHAN_DONG_BASIS",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "基差",
      "id": "1572134912952754177",
      "primaryElement": "基差",
      "relationTemplate": "",
      "secondaryElements": "主力合约",
      "sort": 10,
      "thirdLevelElements": "西南",
      "usingFlag": "1",
      "valueCode": "BASIS_MAIN_CONTRACT_SOUTHWEST_BASIS",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "基差",
      "id": "1572135025230077953",
      "primaryElement": "基差",
      "relationTemplate": "",
      "secondaryElements": "主力合约",
      "sort": 11,
      "thirdLevelElements": "华东",
      "usingFlag": "1",
      "valueCode": "BASIS_MAIN_CONTRACT_EAST_CHINA_BASIS",
      "whetherItem": "0"
  },
  {
      "id": "1572135221297012738",
      "primaryElement": "基差评价",
      "relationTemplate": "",
      "sort": 12,
      "usingFlag": "1",
      "valueCode": "BASIS_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "价格",
      "id": "1572137312920920066",
      "primaryElement": "成本",
      "relationTemplate": "",
      "secondaryElements": "沥青成本",
      "sort": 13,
      "thirdLevelElements": "沥青成本",
      "usingFlag": "1",
      "value": 3753,
      "valueCode": "COST_ASPHALT_COST_PRICE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "盘面裂解利润",
      "id": "1572137751729004545",
      "primaryElement": "利润",
      "relationTemplate": "",
      "secondaryElements": "沥青",
      "sort": 14,
      "thirdLevelElements": "即期利润",
      "usingFlag": "1",
      "valueCode": "CRACKING|PROFIT",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "沥青装置生产利润",
      "id": "1572137954854952962",
      "primaryElement": "利润",
      "relationTemplate": "",
      "secondaryElements": "沥青",
      "sort": 15,
      "thirdLevelElements": "即期利润",
      "usingFlag": "1",
      "valueCode": "ASPHALT|DEVICE|PROFIT",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "汽油装置生产利润",
      "id": "1572138183855562754",
      "primaryElement": "利润",
      "relationTemplate": "",
      "secondaryElements": "成品油",
      "sort": 16,
      "thirdLevelElements": "即期利润",
      "usingFlag": "1",
      "valueCode": "GASOLINE|DEVICE|PROFIT",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "柴油装置生产利润",
      "id": "1572138435127926785",
      "primaryElement": "利润",
      "relationTemplate": "",
      "secondaryElements": "成品油",
      "sort": 17,
      "thirdLevelElements": "即期利润",
      "usingFlag": "1",
      "valueCode": "DIESEL_FUEL|DEVICE|PROFIT",
      "whetherItem": "1"
  },
  {
      "evaluate": "",
      "id": "1572138533941534721",
      "primaryElement": "成本、利润评价",
      "relationTemplate": "",
      "sort": 18,
      "usingFlag": "1",
      "valueCode": "COST_PROFIT_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "区域价差",
      "id": "1572138779098603522",
      "primaryElement": "区域价差",
      "relationTemplate": "",
      "secondaryElements": "西北",
      "sort": 19,
      "thirdLevelElements": "山东",
      "usingFlag": "1",
      "valueCode": "REGION_SPREAD_NORTHWEST_SHAN_DONG",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "区域价差",
      "id": "1572138967003422722",
      "primaryElement": "区域价差",
      "relationTemplate": "",
      "secondaryElements": "西南",
      "sort": 20,
      "thirdLevelElements": "山东",
      "usingFlag": "1",
      "valueCode": "REGION_SPREAD_SOUTHWEST_SHAN_DONG",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "区域价差",
      "id": "1572139162206330881",
      "primaryElement": "区域价差",
      "relationTemplate": "",
      "secondaryElements": "东北",
      "sort": 21,
      "thirdLevelElements": "山东",
      "usingFlag": "1",
      "valueCode": "REGION_SPREAD_NORTHEAST_SHAN_DONG",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "区域价差",
      "id": "1572139276534669313",
      "primaryElement": "区域价差",
      "relationTemplate": "",
      "secondaryElements": "华南",
      "sort": 22,
      "thirdLevelElements": "山东",
      "usingFlag": "1",
      "valueCode": "REGION_SPREAD_SOUTH_CHINA_SHAN_DONG",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "区域价差",
      "id": "1572139411335405569",
      "primaryElement": "区域价差",
      "relationTemplate": "",
      "secondaryElements": "华东",
      "sort": 23,
      "thirdLevelElements": "山东",
      "usingFlag": "1",
      "valueCode": "REGION_SPREAD_EAST_CHINA_SHAN_DONG",
      "whetherItem": "0"
  },
  {
      "id": "1572139503148720129",
      "primaryElement": "区域价差评价",
      "relationTemplate": "",
      "sort": 24,
      "usingFlag": "1",
      "valueCode": "REGION_SPREAD_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572139834800726017",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 25,
      "thirdLevelElements": "齐鲁",
      "usingFlag": "1",
      "valueCode": "91370305723267788H|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572139983958564865",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 26,
      "thirdLevelElements": "齐鲁",
      "usingFlag": "1",
      "valueCode": "91370305723267788H|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572140208735510529",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 27,
      "thirdLevelElements": "华龙",
      "usingFlag": "1",
      "valueCode": "91370523613396124E|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572140373689098241",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 28,
      "thirdLevelElements": "华龙",
      "usingFlag": "1",
      "valueCode": "91370523613396124E|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572140546288902146",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 29,
      "thirdLevelElements": "科力达",
      "usingFlag": "1",
      "valueCode": "913705230562393447|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572140690770092033",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 30,
      "thirdLevelElements": "科力达",
      "usingFlag": "1",
      "valueCode": "913705230562393447|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572140946391949313",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 31,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "SD|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572142116690845697",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "山东",
      "sort": 32,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "SD|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1572143196027871234",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920001",
      "secondaryElements": "山东区域供需及价格评价",
      "sort": 33,
      "usingFlag": "1",
      "valueCode": "SHAN_DONG_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572160601236766722",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华中",
      "sort": 34,
      "thirdLevelElements": "东明",
      "usingFlag": "1",
      "valueCode": "9137172816928036XB|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572161111926833154",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华中",
      "sort": 35,
      "thirdLevelElements": "东明",
      "usingFlag": "1",
      "valueCode": "9137172816928036XB|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572161372879650818",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华中",
      "sort": 36,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "HZ|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572161539976527873",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华中",
      "sort": 37,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "HZ|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1572162087194787841",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920004",
      "secondaryElements": "华中沥青区域供需及价格评价",
      "sort": 38,
      "usingFlag": "1",
      "valueCode": "CENTRAL_CHINA_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572161301064777729",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华北",
      "sort": 39,
      "thirdLevelElements": "鑫海",
      "usingFlag": "1",
      "valueCode": "911309837825909566|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572161494392832002",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华北",
      "sort": 40,
      "thirdLevelElements": "鑫海",
      "usingFlag": "1",
      "valueCode": "911309837825909566|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572161802170859521",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华北",
      "sort": 41,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "HB|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572162024401862658",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华北",
      "sort": 42,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "HB|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1575674485671251970",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920006",
      "secondaryElements": "华北区域供需及价格评价",
      "sort": 43,
      "usingFlag": "1",
      "valueCode": "NORTH_CHINA_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572162565202837505",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "东北",
      "sort": 44,
      "thirdLevelElements": "宝来",
      "usingFlag": "1",
      "valueCode": "91210181MA0U7HED4P|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572162719054102530",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "东北",
      "sort": 45,
      "thirdLevelElements": "宝来",
      "usingFlag": "1",
      "valueCode": "91210181MA0U7HED4P|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572163079403536385",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "东北",
      "sort": 46,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "DB|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572163262078058497",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "东北",
      "sort": 47,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "DB|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1572163865185419265",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920008",
      "secondaryElements": "东北区域供需及价格评价",
      "sort": 48,
      "usingFlag": "1",
      "valueCode": "NORTHEAST_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572162860804800513",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西北",
      "sort": 49,
      "thirdLevelElements": "克炼",
      "usingFlag": "1",
      "valueCode": "9165020033306538XB|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572163028665040897",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西北",
      "sort": 50,
      "thirdLevelElements": "克炼",
      "usingFlag": "1",
      "valueCode": "9165020033306538XB|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572163229458956289",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西北",
      "sort": 51,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "XB|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572163400070660098",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西北",
      "sort": 52,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "XB|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1572163619671834626",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920009",
      "secondaryElements": "西北区域供需及价格评价",
      "sort": 53,
      "usingFlag": "1",
      "valueCode": "NORTHWEST_EVALUATE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572164153103417346",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华东",
      "sort": 54,
      "thirdLevelElements": "镇海",
      "usingFlag": "1",
      "valueCode": "91330200793017426Q|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572164278399860737",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华东",
      "sort": 55,
      "thirdLevelElements": "镇海",
      "usingFlag": "1",
      "valueCode": "91330200793017426Q|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572164413821353985",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华东",
      "sort": 56,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "HD|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572164566900867073",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华东",
      "sort": 57,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "HD|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1575671949220433922",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920007",
      "secondaryElements": "华东区域供需及价格评价",
      "sort": 58,
      "usingFlag": "1",
      "valueCode": "EAST_CHINA_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572163899385774082",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华南",
      "sort": 59,
      "thirdLevelElements": "茂名",
      "usingFlag": "1",
      "valueCode": "91440900194921042C|BU|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572164071926857729",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华南",
      "sort": 60,
      "thirdLevelElements": "茂名",
      "usingFlag": "1",
      "valueCode": "91440900194921042C|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572164213031632897",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华南",
      "sort": 61,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "HN|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572164326420447233",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "华南",
      "sort": 62,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "HN|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1572164432095936513",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920005",
      "secondaryElements": "华南区域供需及价格评价",
      "sort": 63,
      "usingFlag": "1",
      "valueCode": "SOUTH_CHINA_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "日产量",
      "id": "1572163668254457857",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西南",
      "sort": 64,
      "thirdLevelElements": "泸州",
      "usingFlag": "1",
      "valueCode": "91510500754707221T|BU|DAY_Yield",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "开工率",
      "id": "1572163877340512257",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西南",
      "sort": 65,
      "thirdLevelElements": "泸州",
      "usingFlag": "1",
      "valueCode": "91510500754707221T|BU|LQ_KGL",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域日出货量",
      "id": "1572164203535728642",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西南",
      "sort": 66,
      "thirdLevelElements": "区域日出货量",
      "usingFlag": "1",
      "valueCode": "XN|BU|SALE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "区域主流成交价",
      "id": "1572164656424091650",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "西南",
      "sort": 67,
      "thirdLevelElements": "区域主流成交价",
      "usingFlag": "1",
      "valueCode": "XN|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "id": "1572165288736391170",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920003",
      "secondaryElements": "西南区域供需及价格评价",
      "sort": 68,
      "usingFlag": "1",
      "valueCode": "SOUTHWEST_EVALUATE",
      "whetherItem": "0"
  },
  {
      "dataDirectory": "主流成交价",
      "id": "1572165889163591682",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "特种",
      "sort": 69,
      "thirdLevelElements": "90",
      "usingFlag": "1",
      "valueCode": "C01100171|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "主流成交价",
      "id": "1572166075617181698",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "特种",
      "sort": 70,
      "thirdLevelElements": "改性",
      "usingFlag": "1",
      "valueCode": "250397209|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "主流成交价",
      "id": "1572166266101497858",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "特种",
      "sort": 71,
      "thirdLevelElements": "200号",
      "usingFlag": "1",
      "valueCode": "250829278|BU|STRIKE_PRICE",
      "whetherItem": "1"
  },
  {
      "dataDirectory": "出口量",
      "id": "1572166584348508161",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "",
      "secondaryElements": "出口",
      "sort": 72,
      "thirdLevelElements": "出口",
      "usingFlag": "1",
      "valueCode": "CN|BU|EXPORT_VOLUME",
      "whetherItem": "1"
  },
  {
      "id": "1572166909377708033",
      "primaryElement": "沥青区域供需及价格",
      "relationTemplate": "QYLQ20220920002",
      "secondaryElements": "特种区域供需及价格评价",
      "sort": 73,
      "usingFlag": "1",
      "valueCode": "SPECIAL_EVALUATE",
      "whetherItem": "0"
  },
  {
      "id": "1572167057386307586",
      "primaryElement": "沥青区域供需及价格评价",
      "relationTemplate": "",
      "sort": 74,
      "usingFlag": "1",
      "valueCode": "ASPHALT_REGION_EVALUATE",
      "whetherItem": "0"
  },
  {
      "id": "1572167085676888066",
      "primaryElement": "今日策略",
      "relationTemplate": "",
      "sort": 75,
      "usingFlag": "1",
      "valueCode": "STRATEGY",
      "whetherItem": "0"
  }
]
